import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body  >
        <Navbar />
        <main>
        {children}

        </main>
        <footer className="bg-black flex flex-col md:flex-row justify-between gap-10 px-10 py-10">
          <div className="p-10 rounded-2xl border border-black drop-shadow-solid flex flex-col gap-5 justify-between">
            <Link href="/">
              {/* <Image src={logo} alt="Logo" /> */}
              LOGO
            </Link>
          </div>
          {/* <SocialLinks /> */}
        </footer>
      </body>
    </html>
  );
}
